language: python
python:
    - "2.7"
 
install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
 
script:
    - platformio ci examples/dictio --board=uno
